# define java compiler
JC = javac

#define a makefile varible 
JFLAGS = -g

default:
	$(JC) $(JFLAGS) Test.java Option.java MonteCarlo.java Process.java NormalDistribution.java Path.java BSMCalculator.java HestonProcess.java BatesProcess.java PoissonDistribution.java ../math/MatrixAlgebra.java SampleAccumulator.java BSMProcess.java

clean:
	$(RM) *.class
